优化代码结构

diff --git a/.github/workflows/PushPlus_Event.yml b/.github/workflows/PushPlus_Event.yml
--- a/.github/workflows/PushPlus_Event.yml
+++ b/.github/workflows/PushPlus_Event.yml
@@ -38,11 +38,17 @@ jobs:
       run: |
         # 升级pip到最新版本
         python -m pip install --upgrade pip
-        # 安装requests库
-        pip install requests
-        # 安装lunardate库
-        pip install lunardate
-     
+        # 安装所有依赖项，假设依赖项在项目的根目录下的requirements.txt中列出
+        if [ -f requirements.txt ]; then
+          pip install -r requirements.txt
+        else
+          # 如果没有 requirements.txt 文件，则提示用户并停止
+          echo "Error: 未找到 requirements.txt 文件"
+          exit 1
+        fi
+    - name: Set up PYTHONPATH
+        # 确保项目根目录在PYTHONPATH中，以便能够找到pushplus包
+      run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
 
     - name: Run Event reminder script
       # 设置环境变量，并运行事件提醒脚本
@@ -51,6 +57,7 @@ jobs:
         # PUSHPLUS_TOKEN为密钥名称，请根据实际情况修改
         PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
         CalendarAPI_KEY: ${{ secrets.CalendarAPI_KEY }}
+        PUSHPLUS_GROUP_TOPIC: ${{ secrets.PUSHPLUS_GROUP_TOPIC }}
       # 运行指定的Python脚本来执行事件提醒逻辑
       run: |
         # 执行事件提醒脚本
